apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  #  namespace: dev-to
  labels:
    app: myapp
spec:
  replicas: 2
  strategy:
  # indicate which strategy we want for rolling update
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  selector:
    matchLabels:
      app: myapp
  template:
      metadata:
        labels:
          app: myapp
      spec:
        terminationGracePeriodSeconds: 60     
        containers:
          - name: myapp
            image: IMAGE
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                name: http
            envFrom:
              - configMapRef:
                  name: myapp
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 5

